### ISSUE TITLE
Cure sound effect plays globally

### ISSUE THREAD

**Issue by diplomatNSTAR** [xxauroraxx/dnd5e#2]
Whenever the Cleric cure spell is used, the sound effect plays globally to all players. Potentially implement a range so only near by can hear if possible?

**Comment by aurorapar** [comment]
I am still experiencing with the sound engine in Source-Python. There may not be a way to reduce the area the sound plays in.

Leaving issue open for more investigation.

**Comment by aurorapar** [comment]
Created basic sound API for localization. https://github.com/xxauroraxx/dnd5e/commit/473a7f957659422f52252825a7c0d7207fc62386
